version: "3.9"

services:
  telegram-monitor-bot:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    container_name: tg-laptop-monitor
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CHAT_ID=${CHAT_ID}
      - SSH_KEY_LOCATION=${SSH_KEY_LOCATION}
      - SSH_USER_NAME=${SSH_USER_NAME}
    privileged: true
    network_mode: host
    volumes:
      - ${SSH_KEY_HOST_PATH}:/app/ssh:ro # ← path host dari env
      - /sys:/sys:ro
      - /proc:/proc:ro
      - bot-data:/app/data

volumes:
  bot-data:
    driver: local
